### ISSUE TITLE
Unable to fork

### ISSUE THREAD

**Issue by DannyLeeBeasley** [learn-co-curriculum/phase-4-rails-resources-index-show#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas
https://learning.flatironschool.com/courses/4207/assignments/135826?module_item_id=281617
Add a link to the assignment in Canvas here.

## Describe the bug
I was not able to fork the lesson using the blue FORK button nor clicking the octocat logo and clicking Fork in the top left.
Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

## What is the expected behavior?

Write a clear and concise description of what you expected to happen.

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X

**Comment by graciemcguire** [comment]
Hello!
Thanks for raising this issue. We were unable to recreate your issue, and it sounds like the issue may be related to your environment setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved! 💙

**Comment by DannyLeeBeasley** [comment]
Hi Gracie,

I'm pretty sure GitHub was just having problems at that time. Several other
students in my cohort were having the same issue (even on other labs) and
we were having trouble pushing as well. If you kept trying, it would
eventually work, then after an hour or two it just stopped happening, so we
think it was a temporary GitHub issue.

Thanks,

Dan

**Comment by graciemcguire** [comment]
Hey Dan, that might have been what happened. In the future if you think GitHub might be down, check out https://www.githubstatus.com/ ! It's a great resource for any developers using git.

Happy coding!
